"""empty message

Revision ID: 158b08b9d8dc
Revises: e39fcfbe24c7
Create Date: 2023-05-01 15:55:50.840068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158b08b9d8dc'
down_revision = 'e39fcfbe24c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('predict_addr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predict_addr', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
