"""empty message

Revision ID: 5d5b31ab21f5
Revises: 158b08b9d8dc
Create Date: 2023-05-01 15:56:43.111193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5b31ab21f5'
down_revision = '158b08b9d8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('data_id', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('res_addr', sa.String(length=1000), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('data_id', 'model_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict')
    # ### end Alembic commands ###
