"""empty message

Revision ID: bfb3276095e4
Revises: c8c59fd9ad47
Create Date: 2023-05-01 11:28:41.711298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb3276095e4'
down_revision = 'c8c59fd9ad47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnnmodel',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('addr', sa.String(length=1000), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cnnmodel')
    # ### end Alembic commands ###
