"""empty message

Revision ID: c8c59fd9ad47
Revises: 
Create Date: 2023-04-30 16:58:19.718397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c59fd9ad47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ids', sa.String(length=100), nullable=False),
    sa.Column('addr', sa.String(length=1000), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
