"""empty message

Revision ID: e39fcfbe24c7
Revises: bfb3276095e4
Create Date: 2023-05-01 15:48:40.316694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39fcfbe24c7'
down_revision = 'bfb3276095e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predict_addr', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('predict_addr')

    # ### end Alembic commands ###
